version: "3.9"
services:
  web:
    build: 
      context: "." 
      no_cache: true
      platforms:
        - "linux/amd64"
    ports:
      - "9292:9292"
    volumes:
      - .:/trailjournals
    command: bundler exec rackup --env production
